In [4]:
import torch

In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
Y = torch.tensor([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
Y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
X == Y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [9]:
X != Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [10]:
X[0,0] = 1
X

tensor([[ 1,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
X == Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [14]:
X,Y,X < Y

(tensor([[ 1,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [15]:
X,Y,X > Y

(tensor([[ 1,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ True, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [19]:
X = torch.arange(12).reshape(-1,6)
X

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [20]:
Y = torch.randn(1,6)
Y

tensor([[ 1.0478, -0.2208, -0.1156, -0.3736, -0.2128,  0.4177]])

In [22]:
X,Y,X + Y

(tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]),
 tensor([[ 1.0478, -0.2208, -0.1156, -0.3736, -0.2128,  0.4177]]),
 tensor([[ 1.0478,  0.7792,  1.8844,  2.6264,  3.7872,  5.4177],
         [ 7.0478,  6.7792,  7.8844,  8.6264,  9.7872, 11.4177]]))

In [28]:
X = torch.arange(12).reshape(2,3,2)
Y = torch.arange(3).reshape(1,3,1)
X,Y,X + Y

(tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]]]),
 tensor([[[0],
          [1],
          [2]]]),
 tensor([[[ 0,  1],
          [ 3,  4],
          [ 6,  7]],
 
         [[ 6,  7],
          [ 9, 10],
          [12, 13]]]))

In [30]:
X

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

In [ ]:
X,X.numel(),torch.zeros_like(X),X.exp(),X.exp2()

(tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]]]),
 12,
 tensor([[[0, 0],
          [0, 0],
          [0, 0]],
 
         [[0, 0],
          [0, 0],
          [0, 0]]]),
 tensor([[[1.0000e+00, 2.7183e+00],
          [7.3891e+00, 2.0086e+01],
          [5.4598e+01, 1.4841e+02]],
 
         [[4.0343e+02, 1.0966e+03],
          [2.9810e+03, 8.1031e+03],
          [2.2026e+04, 5.9874e+04]]]),
 tensor([[[1.0000e+00, 2.0000e+00],
          [4.0000e+00, 8.0000e+00],
          [1.6000e+01, 3.2000e+01]],
 
         [[6.4000e+01, 1.2800e+02],
          [2.5600e+02, 5.1200e+02],
          [1.0240e+03, 2.0480e+03]]]))

In [37]:
print(id(X))
X = X + 1
print(id(X))

2181177276352
2181176653760


In [38]:
print(id(X))
X[:] = X + 1
print(id(X))

2181176653760
2181176653760


In [39]:
print(id(X))
X += 1
print(id(X))

2181176653760
2181176653760


In [51]:
X = torch.tensor(12)
X

tensor(12)

In [52]:
X.item(),float(X),int(X)

(12, 12.0, 12)

In [53]:
X.numpy(),type(X)

(array(12, dtype=int64), torch.Tensor)

In [54]:
X = X.numpy()
type(X)

numpy.ndarray