In [4]:
import torch

In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
Y = torch.tensor([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
Y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
X == Y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [9]:
X != Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [10]:
X[0,0] = 1
X

tensor([[ 1,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
X == Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [14]:
X,Y,X < Y

(tensor([[ 1,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [15]:
X,Y,X > Y

(tensor([[ 1,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ True, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [19]:
X = torch.arange(12).reshape(-1,6)
X

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [20]:
Y = torch.randn(1,6)
Y

tensor([[ 1.0478, -0.2208, -0.1156, -0.3736, -0.2128,  0.4177]])

In [22]:
X,Y,X + Y

(tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]),
 tensor([[ 1.0478, -0.2208, -0.1156, -0.3736, -0.2128,  0.4177]]),
 tensor([[ 1.0478,  0.7792,  1.8844,  2.6264,  3.7872,  5.4177],
         [ 7.0478,  6.7792,  7.8844,  8.6264,  9.7872, 11.4177]]))

In [28]:
X = torch.arange(12).reshape(2,3,2)
Y = torch.arange(3).reshape(1,3,1)
X,Y,X + Y

(tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]]]),
 tensor([[[0],
          [1],
          [2]]]),
 tensor([[[ 0,  1],
          [ 3,  4],
          [ 6,  7]],
 
         [[ 6,  7],
          [ 9, 10],
          [12, 13]]]))